# https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/docker-compose/docker-compose.yaml
version: "3.7"
services:
  postgres:
    container_name: db-hasura
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: VGSxdjsYnC

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    container_name: hasura
    depends_on:
      - "postgres"
      - "api"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:VGSxdjsYnC@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: VGSxdjsYnC
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "enerfit-api", "issuer": "https://securetoken.google.com/enerfit-api","claims_map": {"x-hasura-allowed-roles": ["user"],"x-hasura-default-role": "user","x-hasura-user-id": {"path":"$$.user_id"}}}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

  api:
    build: ./nest-auth
    restart: always
    container_name: api-nest
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    volumes:
      - ./nest-auth/assets/enerfit-api-firebase-adminsdk-w6zi4-096e7553bc.json:./enerfit-api-firebase-adminsdk-w6zi4-096e7553bc.json
    environment:
      TZ: America/Santiago

volumes:
  db_data:
