version: '3'
services:
  api:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - '3000:3000'

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      TZ: 'America/Santiago'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

    redis:
      image: redis:alpine
      restart: always
      ports:
        - '6379:6379'
      volumes:
        - ./db/redis_data:/data
